// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDow5Y5_-HQTGrpTgRhbW8PceiB1zzAdLE',
    appId: '1:955502920661:web:e90628c463d2446950335c',
    messagingSenderId: '955502920661',
    projectId: 'todo-firebase-926a8',
    authDomain: 'todo-firebase-926a8.firebaseapp.com',
    storageBucket: 'todo-firebase-926a8.appspot.com',
    measurementId: 'G-JB3YKPRBC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADmKjqi9VDIeOT-uzouHv4SuY7wnF-wT0',
    appId: '1:955502920661:android:2fd71de73a3ac4e050335c',
    messagingSenderId: '955502920661',
    projectId: 'todo-firebase-926a8',
    storageBucket: 'todo-firebase-926a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXR_m97W-EYR-Rjfaq5Eur1l9U9YO1hzE',
    appId: '1:955502920661:ios:1d26dbb48b3f108150335c',
    messagingSenderId: '955502920661',
    projectId: 'todo-firebase-926a8',
    storageBucket: 'todo-firebase-926a8.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXR_m97W-EYR-Rjfaq5Eur1l9U9YO1hzE',
    appId: '1:955502920661:ios:1d26dbb48b3f108150335c',
    messagingSenderId: '955502920661',
    projectId: 'todo-firebase-926a8',
    storageBucket: 'todo-firebase-926a8.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDow5Y5_-HQTGrpTgRhbW8PceiB1zzAdLE',
    appId: '1:955502920661:web:d53b6f8c317f5e3650335c',
    messagingSenderId: '955502920661',
    projectId: 'todo-firebase-926a8',
    authDomain: 'todo-firebase-926a8.firebaseapp.com',
    storageBucket: 'todo-firebase-926a8.appspot.com',
    measurementId: 'G-3GNZ04QZ0D',
  );
}
